services:
  nodeapp:
    build: ./nodeapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: MONGO_URL=mongodb+srv://user:<your-password>@<your-cluster-name>.mongodb.net/your-database

