services:
  nodeapp:
    build: ./nodeapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: mongodb+srv://admin:qwerty%40123@student-cluster.mrtyhyg.mongodb.net/mydb

